scr/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from places import views

handler404 = views.handler404
handler500 = views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'), name="login"),
    path('', include("social_django.urls"), name="social"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('places/', include('places.urls', namespace='places')),
]

scr/places/urls.py
from django.urls import path
from .views import *

app_name = 'places'

urlpatterns = [
    path('add_place/', add_place, name='add_place'),
    path('', places, name="places"),
    path('<slug:slug>', place_detail, name='place_detail'),
    path('delete/<slug:slug>/', place_delete, name='delete_place'),
]

scr/users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', welcome),
]

scr/places/models.py
from django.db import models
from django.shortcuts import reverse
from users.models import Profile
from django.utils.text import slugify
from transliterate import translit
import re
from datetime import datetime


class Place(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    comment = models.TextField(blank=True, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    class Meta:
        app_label = 'places'

    def save(self, *args, **kwargs):
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        slug = slugify(translit(self.title.__str__(), "ru", reversed=True), allow_unicode=True)
        slug = re.sub(r'[^a-zA-Z0-9_-]', '', slug)  # Исключаем специальные символы
        self.slug = f"{slug}-{self.pk}-{timestamp}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('place_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

scr/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.CharField(max_length=255, null=True, blank=True)

    def get_name_and_avatar(self):
        name = f'{self.user.first_name} {self.user.last_name}'
        return {"name": name, "avatar": self.avatar}

    def __str__(self):
        return f"User: {self.user.username}"

scr/places/forms.py
import re
from django import forms
from .models import Place
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify

class AddPlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ['title', 'location', 'comment']

    def clean_title(self):
        title = self.cleaned_data['title']
        slug = slugify(title, allow_unicode=True)

        if self.instance.pk is None or title != self.initial['title']:
            place_exists = Place.objects.filter(
                models.Q(title=title) | models.Q(slug=slug)
            ).exists()

            if place_exists:
                raise ValidationError('Место с таким названием или слагом уже существует.')

        if not re.match(r'^[\w\s.-]+$', title):
            raise ValidationError('Название места содержит недопустимые символы.')

        return title

    def save_form(self, profile):
        new_place = Place.objects.update_or_create(
            title=self.cleaned_data['title'],
            location=self.cleaned_data['location'],
            comment=self.cleaned_data['comment'],
            profile=profile
        )
        return new_place

scr/places/views.py
from django.contrib.auth.decorators import login_required
from places.models import Place
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddPlaceForm
from config.settings import yandex_api_key


@login_required
def places(request):
    profile_places = Place.objects.filter(profile=request.user.profile)
    return render(request, 'places.html', {'profile_places': profile_places})


@login_required
def add_place(request):
    api_key = yandex_api_key
    if request.method == 'POST':
        form = AddPlaceForm(request.POST)
        if form.is_valid():
            place = form.save(commit=False)
            place.profile = request.user.profile
            place.save()
            return redirect('places:places')
    else:
        form = AddPlaceForm()

    return render(request, 'add_place.html', {'form': form, 'api_key': api_key})


@login_required
def place_detail(request, slug):
    place = get_object_or_404(Place, slug=slug)
    api_key = yandex_api_key

    if request.method == 'POST':
        form = AddPlaceForm(request.POST, instance=place)
        if form.is_valid():
            form.save()
            return redirect('places:places')
    else:
        form = AddPlaceForm(instance=place)

    return render(request, 'place_detail.html', {'form': form, 'place': place, 'api_key': api_key})


@login_required
def place_delete(request, slug):
    place_to_delete = Place.objects.get(profile=request.user.profile, slug__iexact=slug)
    place_to_delete.delete()
    return redirect('places:places')


def handler404(request, exception):
    return render(request, 'errors/404.html', status=404)


def handler500(request):
    return render(request, 'errors/500.html', status=500)

scr/users/views.py
from django.shortcuts import render, redirect


def welcome(request):
    if request.user.is_authenticated:
        return redirect('places:places')
    return render(request, 'welcome_page.html')

scr/templates/add_place.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1>Добавить новое место</h1>
    <div id="map" style="width: 100%; height: 400px;"></div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="place_location">Местоположение</label>
            <input type="text" class="form-control" id="place_location" name="location"
                   placeholder="Поставьте точку на карте" readonly>
            {% if form.location.errors %}
            <small class="form-text text-danger">{{ form.location.errors.0 }}</small>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="place_title">Название места</label>
            <input type="text" class="form-control" id="place_title" name="title" placeholder="Название места">
            {% if form.title.errors %}
            <small class="form-text text-danger">{{ form.title.errors.0 }}</small>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="place_comment">Комментарий</label>
            <textarea class="form-control" id="place_comment" name="comment"
                      placeholder="Комментарий к месту"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Добавить</button>
        <a href="/" class="btn btn-secondary">Назад</a>
    </form>
</div>

<script src="https://api-maps.yandex.ru/2.1/?apikey={{api_key}}&lang=ru_RU" type="text/javascript"></script>
<script type="text/javascript">
        ymaps.ready(init);

        function init() {
            var myMap = new ymaps.Map('map', {
                center: [55.76, 37.64],
                zoom: 10
            });

            var placemark;

            myMap.events.add('click', function (e) {
                var coords = e.get('coords');
                if (placemark) {
                    myMap.geoObjects.remove(placemark);
                }
                placemark = new ymaps.Placemark(coords);
                myMap.geoObjects.add(placemark);
                document.getElementById('place_location').value = coords.join(', ');
            });
        }

</script>
{% endblock %}

scr/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Places Remember - {% block title %}{% endblock %}</title>
    <!-- Подключение стилей Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<style>
    @media (max-width: 767px) {
  .navbar-nav.ml-auto .nav-item {
    display: flex;
    align-items: center;
    justify-content: flex-end;
  }

  .navbar-nav.ml-auto .nav-item .navbar-text {
    margin-right: 10px;
  }

  .navbar-nav.ml-auto .nav-item .btn {
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
  }
}

</style>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Places Remember</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item mr-2 d-flex">
                    <span class="navbar-text">
                        Пользователь:  {{ user.first_name }} {{ user.last_name }}
                    </span>
            </li>
            <li class="nav-item d-flex">
                <img src="{{ user.profile.avatar }}" id="user_avatar" width="40" height="40" class="mr-2">
            </li>
            <li class="nav-item ml-2 d-flex">
                <a class="nav-link btn btn-primary text-white" href="/logout">Выход</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<!-- Основное содержимое страницы -->
{% block content %}{% endblock %}

<!-- Подключение скриптов Bootstrap -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    </ul>
    <p class="text-center text-muted">&copy; 2023 DexTea</p>
</footer>
</body>
</html>

scr/templates/place_detail.html
<!-- place_detail.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1>Редактирование места</h1>
    <div id="map" style="width: 100%; height: 400px;"></div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="place_location">Местоположение</label>
            <input type="text" class="form-control" id="place_location" name="location"
                   value="{{ place.location }}" readonly>
        </div>
        <div class="form-group">
            <label for="place_title">Название места</label>
            <input type="text" class="form-control {% if form.errors.title %}is-invalid{% endif %}" id="place_title"
                   name="title" value="{{ place.title }}">
            {% if form.errors.title %}
            <div class="invalid-feedback">{{ form.errors.title }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="place_comment">Комментарий</label>
            <input type="text" class="form-control {% if form.errors.title %}is-invalid{% endif %}" id="place_comment"
                   name="comment" value="{{ place.comment }}">
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'places:delete_place' place.slug %}" class="btn btn-danger ml-2">Удалить</a>
        <a href="/" class="btn btn-secondary ml-2">Назад</a>
    </form>
</div>

<script src="https://api-maps.yandex.ru/2.1/?apikey={{ api_key }}&lang=ru_RU" type="text/javascript"></script>
<script type="text/javascript">
    ymaps.ready(init);

    function init() {
        var myMap = new ymaps.Map('map', {
            center: [{{ place.location }}],
            zoom: 10
        });

        var placemark = new ymaps.Placemark([{{ place.location }}], {
            draggable: true
        });
        myMap.geoObjects.add(placemark);

        placemark.events.add('dragend', function (e) {
            var coords = placemark.geometry.getCoordinates();
            document.getElementById('place_location').value = coords.join(', ');
        });

        myMap.events.add('click', function (e) {
            var coords = e.get('coords');
            placemark.geometry.setCoordinates(coords);
            document.getElementById('place_location').value = coords.join(', ');
        });
    }

</script>
{% endblock %}

scr/templates/places.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-4">
    <h1>Мои места</h1>
    <div class="container mt-4" id="places">
        {% for place in profile_places %}
        <div class="card text-center border-muted">
            <div class="card-body">
                <h5 class="card-header">{{ place.title }}</h5>
                <p class="text-muted">{{ place.location }}</p>
                <p class="card-text">{{ place.comment }}</p>
                <a href="{{place.slug}}" class="btn btn-primary btn-details">Изменить</a>
                <a href="{% url 'places:delete_place' place.slug %}" class="btn btn-danger">Удалить</a>
            </div>
        </div>
        <p></p>
        {% endfor %}
    </div>

    {% if not profile_places %}
    <div class="text-center mt-4">
        <h3>У вас нет сохраненных мест, {{user.first_name}}</h3>
    </div>
    {% endif %}

    <div class="text-center mt-4">
        <a class="btn btn-primary" href="add_place/">Добавить место</a>
    </div>
</div>
{% endblock %}

scr/templates/welcome_page.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center mt-4">
    <h1>Добро пожаловать в Places Remember!</h1>
    <p>Places Remember - сервис, позволяющий отслеживать ваши любимые места и воспоминания.</p>
    <p>Войдите в свою учетную запись VK, чтобы начать использование сервиса:</p>
    <a class="btn btn-primary" href="/login/vk-oauth2/">Войти через VK</a>
</div>
{% endblock %}